### ISSUE TITLE
Ecode stealing focus on KDE Plasma

### ISSUE THREAD

**Issue by emeraldtip** [SpartanJ/ecode#104]
After a while of having ecode open on KDE it doesn't let me focus on other windows by clicking on them or using the touch screen, I have to alt tab to switch to another window

**Comment by SpartanJ** [comment]
Mmhh that doesn't sound like an ecode bug. If possible try to upload a video demonstrating the issue. Maybe you set the window as always on top by accident or with some shortcut?

**Comment by emeraldtip** [comment]
Sorry for the long wait time, have been busy with studies and stuff.
This happens in i3 aswell, so it can't be a plasma always on top.

I guess I could have a friend test this aswell and see if it's reproducable?

**Comment by SpartanJ** [comment]
I don't understand how can a regular window steal focus on X11, I haven't seen that in ages (I'm a Linux user BTW, so I use ecode mainly on Linux). May be we are talking about different things, but focus stealing is something most Window Managers don't allow these days ([reference](https://en.wikipedia.org/wiki/Focus_stealing)). ecode doesn't have access to control the window focus at all, but it can demand the attention from the user (it's only used when a build is completed). What it should do in that case is flashing the window in the taskbar, but the behavior is controlled by the Window Manager, so that might have something to do with that? I try to use Plasma an check for any weird behavior, but if you mentioned that happens on i3 that sounds that we are talking of different things, becaues i3 is a tiling WM, and for sure you can't steal focus there.

**Comment by emeraldtip** [comment]
I think it somehow registers all mouse clicks outside the window as being within the window somehow, I'll try to record it

**Comment by SpartanJ** [comment]
Oh! I know what you're referring to! When you any dragging operation the UI needs to capture the mouse until the mouse button is released in order to be able to drag or scroll any element from outside the window. So the bug is for sure that the mouse is not being released after being captured with some operation. In the editor there are two major possibilities: when dragging a tab or when scrolling. I'll try to find any possible case when this can fail, it took me a while to get it "right", so I have no doubt that there must be some pending issue to resolve.

**Comment by SpartanJ** [comment]
@emeraldtip Have you encountered this issue again? I've never been able to reproduce it so I can't do much, I understand the issue though.

**Comment by emeraldtip** [comment]
I haven't.
I'll see today, whether I can reproduce it and if I can't, I suppose it's solved

**Comment by SpartanJ** [comment]
I'll close it for the moment.
