### ISSUE TITLE
Middle click drag scroll function idea

### ISSUE THREAD

**Issue by acaxxx** [SpartanJ/ecode#108]
Hi
Would it be possible to implement something like this: when you hold middle-click (on it's own or with a modifier key) and move around it scrolls the document in all directions.

**Comment by SpartanJ** [comment]
It's possible but I haven't found a good reason to implement it, there are also some issues because it conflicts with other gestures. [Here's](https://github.com/SpartanJ/ecode/issues/47#issuecomment-1426809815) a comment regarding that issue. I'll close this issue because it's duplicated, we can continue the conversation [here](https://github.com/SpartanJ/ecode/issues/47). I'm open to discuss for a solution that's good enough for all the use cases.
