### ISSUE TITLE
[FEATURE/BUG] Closing Symbol Override

### ISSUE THREAD

**Issue by NullPlane** [SpartanJ/ecode#121]
I do not know if it is supposed to work or not yet implemented, but 
when activating automated bracket-/tag-closing and then manually
closing a bracket/tag there'll be one closing bracket surplus.

Would be nice if it got replaced. But then only the automatically 
generated bracket and correct layer, so you can close other brackets
inside first before replacing the correct layer (often saw LaTeX-editors 
not layering, so I know to appreciate it if it was a feature too...).

**Comment by SpartanJ** [comment]
The problem with trying to do things in a "smarter" way is that the editor has to guess what was the user intention in the first place, the situation you describe could be exactly what the user intended. I don't know if there's a way to create a set of rules that it's better for all cases. That's why currently the editor will simply do what it's suppose to do, just auto-insert.

Maybe I can add an optional rule that defines that: never double insert same open or close tag when there's one at cursor position. So it should cover two cases:
instead of
`(` -> `(()`
would do
`(` -> `()`

and instead of:

`()` -> `())`
would simply ignore the last insert:
`()` -> `()`

And also should allow to insert the character if tries one more time.
But I don't know, I'm not convinced. I never use auto-insert because I always ends up double inserting things. Maybe you can come up with a set of rules that are good enough for most scenarios, it must be generic and not know anything about the abstract syntax tree.

**Comment by iahung3** [comment]
The rule of thumb is the brackets must be balanced. It's just that. Very simple.

**Comment by SpartanJ** [comment]
We can do that :+1:

**Comment by iahung3** [comment]
We only have to care about the opening brackets. Whatever the users do what the closing brackets, e.g: insert more closing brackets than needed, it's their own problem. Most popular text editors, including IDEs, simply do it like this.

**Comment by SpartanJ** [comment]
OK, I added proper closing symbol override and balanced auto-close. I think it feels nice, I'll try to use it and see how it feels.
