### ISSUE TITLE
[BUG/ENHANCEMENT] WIN Clipboard History not working

### ISSUE THREAD

**Issue by NullPlane** [SpartanJ/ecode#123]
Currently it is not possible to use clipboard history ( [WIN] + [V] ) to paste to the editor or anywhere else; merely the current top-level entry and last copied items may be pasted.

**Comment by SpartanJ** [comment]
Today I learned that exists. I left Windows too many years ago. Let me see what can I do. Thanks for reporting it.

**Comment by SpartanJ** [comment]
I'm reading the documentation and selection any element from that clipboard it does not generate a paste event, but generates a clipboard update (because it updates the current clipboard selection). I tried to detect the clipboard updates but it generates many problems because a clipboard update does not need to correspond to a subsequent paste operation. I won't insist much with this because I can't find any reliable information on how it works on other applications. Maybe if you find an open source editor where this works I can take a look. I'll consider this ticket as an enhancement because it's not a defined behaviour of the operating system, what a wanted integration with an OS application.

**Comment by NullPlane** [comment]
KDE Kate does it definitely but I tried to look into their repo before and it is quite _"entangled"_ and hard to find sht in my personal opinion. You may take a peek if you wish, maybe you find it in time.

**Comment by SpartanJ** [comment]
Fixed in the [latest SDL2 release](https://github.com/libsdl-org/SDL/releases/tag/release-2.30.3). ecode will ship with this SDL2 version.
