### ISSUE TITLE
Feature request: search in folder improvement

### ISSUE THREAD

**Issue by iahung3** [SpartanJ/ecode#150]
Allow specifying the file extensions to search. For example, the directory contains both C#, Java, and C++ source files. But I only want to search in C++ source files (.h and .cpp extensions).

**Comment by emeraldtip** [comment]
I'm fairly certain you could use Lua patterns for that

**Comment by iahung3** [comment]
> I'm fairly certain you could use Lua patterns for that

And I'm certainly I will not use it! Even though I come from Lite XL, I'm not a die hard user of it. I'm in no way a Lua lover, too. The only time I tried to learn Lua Pattern is when I have to write new lexer for Lite XL to add syntax highlighting for a new programming language. But very soon after that, I forgot everything. You see, Lua Pattern can't get into my head. And I hate it.

Yeah, Lua Pattern is in no way as powerful as Regular Expressions, too. For complex enough lexers, you still have to use Regular Expressions in Lite XL. I used to write lexer for TextAdept, too. I admit that I really think LPeg is much better than Lua Pattern.

**Comment by SpartanJ** [comment]
File names cannot be filtered with Lua patterns because they are used for the file contents not the file path. This feature will be added.

**Comment by SpartanJ** [comment]
This has been implemented in develop. You can now include or exclude files with glob patterns, the same way that it works in `sublime_text`. So basically if you want to filter all .lua files you will set `*.lua` as a filter. To exclude we will use "-" to invert the glob pattern (same as sublime), so instead of `*.lua` you'll write `-*.lua`. You can set as many patterns as needed separated by comma. So if you want to filter for example two different extensions you can do something like `*.lua,*.cpp`. It's possible to filter sub-directories and any kind of path that can be filtered with glob.
