### ISSUE TITLE
Feature request: add AdeptLSP

### ISSUE THREAD

**Issue by iahung2** [SpartanJ/ecode#157]
https://github.com/AdeptLanguage/AdeptLSP

**Comment by SpartanJ** [comment]
Support added but the LSP is currently useless, it does very little to nothing and has bugs.

**Comment by iahung2** [comment]
> Support added but the LSP is currently useless, it does very little to nothing and has bugs.

Yes, I know. I asked you to add it to ecode because I didn't know I could add my own local `lspclient.json`.

**Comment by SpartanJ** [comment]
Yep! The idea is to let the user extend the capabilities of ecode as easily as possible. Some LSPs use particular configurations that are specific for each client. AdeptLSP is one of those cases but I added a new feature that should work very well for other particular cases as this one.
I added [vars](https://github.com/SpartanJ/eepp/commit/70c1c4daa5ece0b5868bd8e6a42f1d76b37af7d9#diff-c48dd0d8302731eb10553c51a1f4a486ce2d49187d3111f0bf37e891b8c72e08R304) to the configuration, each var is a defined variable taken from the environment by running an specific command, in this case we needed the adept root path obtained with `adept --root`, so I defined a var for that and the stdout of that command will be used for that variable defined in the command. That should give us great flexibility.
It was also valuable for us because AdeptLSP crashed ecode when the LSP was being closed at some occasions and that fix should be nice for other LSPs.
