### ISSUE TITLE
Feature request: import TextAdept lexers

### ISSUE THREAD

**Issue by iahung3** [SpartanJ/ecode#176]
https://github.com/orbitalquark/scintillua/tree/default/lexers

**Comment by SpartanJ** [comment]
This is something I already considered but I'm not sure if it's worth it. We can quite easily manually port any of the languages supported by schintillua to ecode, I'm pretty sure I already did that for a couple of languages, it's just a matter of doing it.

**Comment by iahung3** [comment]
> This is something I already considered but I'm not sure if it's worth it. We can quite easily manually port any of the languages supported by schintillua to ecode, I'm pretty sure I already did that for a couple of languages, it's just a matter of doing it.

It's not always easy to port from LPeg to Lua Pattern. If you could support LPeg, it would be much better.

**Comment by SpartanJ** [comment]
I have been taking a look and it does not seem easily feasible. I would need to integrate lua + lpeg + scintillua lexer. I still think that porting most of the languages from scintillua is pretty easy. I think that what makes more sense is to implement a translator tool from scintillua to ecode or even lite since we can translate from there too. That one wouldn't be hard.

**Comment by iahung3** [comment]
> I think that what makes more sense is to implement a translator tool from scintillua to ecode or even lite since we can translate from there too. That one wouldn't be hard.

I don't think such a tool is easy to implement. Finally, we still have to resort to translating manually.
