### ISSUE TITLE
Discussion: TextMate bundles

### ISSUE THREAD

**Issue by iahung3** [SpartanJ/ecode#191]
This will be something very large to implement, but it will be very useful in the long term, too. It is becoming a standard now. Even Eclipse IDE added support for it. All of this is thanks to the popularity of VSCode.

@SpartanJ What do you think about this?

**Comment by SpartanJ** [comment]
There are a few steps that must be done before being able to support bundles. First ecode must support regex in language grammars. Then it must support [TextMate language grammars](https://macromates.com/manual/en/language_grammars). But before doing that I need to analice the performance of using language grammars with regex with PCRE2. All of this is a good amount of work, to do all this work there must be a good motivation and must be worth it. As for the moment I don't see any particular example of why we should implement this now (and not later with a more mature editor). The main issue is that I'm working alone on all these features, and I work on my free time just for fun, so almost every feature I add is mostly because I need it. So if you ask me: this sounds great on paper, I would love to do it, but it won't happen soon (except for the regex support, which I want to have it). Currently [these](https://github.com/SpartanJ/ecode?tab=readme-ov-file#planned-features) are my priorities for big features (and DAP support is the first I want of all of them).
