### ISSUE TITLE
[Bug] Syntax highlighting

### ISSUE THREAD

**Issue by iahung3** [SpartanJ/ecode#201]
This happens with all Lite-based editors. But it's most serious with ecode. My machine is powerful enough. So, please don't tell me to upgrade 😄 

When you open a shell script or a perl script (maybe other file types, too), and the file itself doesn't have to be large, sometimes some keywords are not highlighted. You have to close the file and reopen it again to have it correctly highlight them.

It's most serious with SmallBASIC. Some keywords, e.g., `const`, `func`, `sub`, etc., are not highlighted at all, even if you close the file and reopen it again. I found that if you type the keywords (`const`, `func`, `sub`, etc.) from scratch, they are correctly highlighted. So, I tried to insert a space after the keywords (`const`, `func`, `sub`, etc.) in existing code, and guess what? They are now correctly highlighted 😂

**Comment by iahung3** [comment]
It also happens with C++ source file. For example, `#include <iostream>` is not highlighted. If I close and reopen the file, it is now correctly highlighted. If you want SmallBASIC example code then here you are:

https://github.com/smallbasic/SmallBASIC/blob/master/samples/distro-examples/graphics/3dtorus.bas

**Comment by SpartanJ** [comment]
> It also happens with C++ source file. For example, #include <iostream> is not highlighted.

That's very strange, I have never seen anything like that in C++. You're seeing it with my code?

>  If you want SmallBASIC example code then here you are:

This one I can reproduce it, it's selecting Visual Basic by error, so it's highlighted because it's actually using other grammar, but I already send a fix [here](https://github.com/SpartanJ/eepp/commit/fdc9a55809fa53420fd55d8a679ecc155334dbeb) so thanks for reporting it. But besides that MANY keywords are not being highlighted because SmallBASIC has incorrect definitions of the symbols, basically symbols are case sensitive, if you defined "Sub" but the file uses "SUB" it will not be highlighted. So SmallBASIC needs fixes. Checking the definition file many words are repeated, I think it's because they were in upper case and lower case and for some reason when you copied them all where transformed to lower-case, I corrected some of them, but please try to fix them and send a patch.

**Comment by SpartanJ** [comment]
> It also happens with C++ source file. For example, #include is not highlighted.

Also please send me an example, C++ should have really good highlighting since I used for many hours a day every single day. This must be something weird.

**Comment by iahung3** [comment]
I can't give you the specific C++ source file. This happens randomly, but is very likely to happen. And it can happen with any C++ source file.

**Comment by SpartanJ** [comment]
> If you want SmallBASIC example code then here you are:

To clarify, also any new code was being highlighted correctly so you ended up with some mixed grammars between Visual Basic and SmallBASIC.

> When you open a shell script or a perl script (maybe other file types, too), and the file itself doesn't have to be large, sometimes some keywords are not highlighted. You have to close the file and reopen it again to have it correctly highlight them.

Regarding this, please if you still encounter it send me the file.

**Comment by iahung3** [comment]
> Regarding this, please if you still encounter it send me the file.

It happens randomly (but is more likely to happen than not). I can't send you a specific file.

**Comment by SpartanJ** [comment]
> I can't give you the specific C++ source file. This happens randomly but is more likely to happen than not. And it can happen with any C++ source file.

My guess is that you're talking about `.h` files which can be interpreted as C or C++ source code, in that case there's an specific option for that in `Settings -> Folder/Project Settings -> Treat .h files as C++ code.`.

**Comment by SpartanJ** [comment]
> It happens randomly (but is more likely to happen than not). I can't send you a specific file.

Whenever you find a find where it happens randomly and it's shareable please send it.

**Comment by iahung3** [comment]
> > I can't give you the specific C++ source file. This happens randomly but is more likely to happen than not. And it can happen with any C++ source file.
> 
> My guess is that you're talking about `.h` files which can be interpreted as C or C++ source code, in that case there's an specific option for that in `Settings -> Folder/Project Settings -> Treat .h files as C++ code.`.

No, it's a `.cpp` source file.

**Comment by iahung3** [comment]
Btw, instead of inserting multiple versions of the keywords in different cases like you are currently doing on https://github.com/SpartanJ/eepp/commit/fdc9a55809fa53420fd55d8a679ecc155334dbeb#diff-cc2a4072b6f5f4fee64f71c08841e3ef1f61ab57e5241b0b1bf08bb583c375e2, why don't you add an option to treat the keywords as case insensitive? There are a lot of languages that are case insensitive. If it's broken for SmallBASIC, it's broken for these languages, too.

**Comment by SpartanJ** [comment]
For performance reasons. Most languages are case-sensitive so it's not a big deal.

**Comment by iahung3** [comment]
The problem with SmallBASIC is fixed. The problem of randomly missing some keywords from syntax highlighting is common to all Lite-based editors so I don't think too serious. You can mark this issue as solved. Btw, thank you.

**Comment by iahung2** [comment]
Today I encountered this bug again. Take this very simple `test.adept` file:

```
import basics

func main() void {
	print("foo")
}
```

The `import` keyword is not highlighted. Even if you close and reopen the file again, it's still not highlighted. To have it highlighted, you need to put the cursor after it and press `Space`. This is a temporary workaround because if you close and reopen the file again, the keyword `import` is still not highlighted.

**Comment by SpartanJ** [comment]
I noticed something similar, there seems to be a problem with the first line of the file, but it happens randomly for me, I cannot always replicate it, it must be something trivial to fix but I'm finding it hard to reproduce.
