### ISSUE TITLE
Feature request: add objeck-lsp

### ISSUE THREAD

**Issue by iahung2** [SpartanJ/ecode#203]
https://github.com/objeck/objeck-lsp

**Comment by SpartanJ** [comment]
objeck-lsp is already supported but I cannot distribute a default configuration for the editor since there's no generic way to run it. But support has been added, check this [issue](https://github.com/SpartanJ/ecode/issues/95).
The LSP needs the following command to run:
`<objeck_path>/bin/obr.exe "<objeck_server_path>/objeck_lsp.obe" <objeck_server_path>/objk_apis.json" stdio`
Plus setting an a couple of environment variables, which one of them is a custom path:
`"OBJECK_LIB_PATH": "<objeck_path>/lib"`
`"OBJECK_STDIO": "binary"`

I can't do much about it, maybe you can request the author to provide a generic package.

**Comment by SpartanJ** [comment]
No, you don't need to configure anything else, if the LSP provides the features you only need the formatter and linter plugin to be active, they will detect that the feature is provided by the LSP and consume it. I think I'll add some notice in the language list when the feature is provided by the LSP. You can also have an LSP with formatter and linter plugin but set separately the formatter or linter. For formatter it will try to prioritise the formatter binary. The linter consumes both applications at the same time, so you'll have code analysis from both which is really useful on some cases (for example clangd + cpp-check).
