### ISSUE TITLE
Discussion: Use alternative terminal emulator for legacy Windows?

### ISSUE THREAD

**Issue by iahung3** [SpartanJ/ecode#207]
Windows Terminal is not available. But there are other terminal emulators available for Windows:

https://alternativeto.net/software/cmder/?platform=windows

Related (and maybe supercede): https://github.com/SpartanJ/ecode/issues/153

**Comment by superchick** [comment]
ConEmu can be embedded into other applications.

**Comment by iahung3** [comment]
If it's too involved we can fall back to https://github.com/SpartanJ/ecode/issues/153.

**Comment by SpartanJ** [comment]
As I said before, I won't do any effort to add terminal support for Win8.1 and before. It's not worth the effort given how [niche](https://gs.statcounter.com/os-version-market-share/windows/desktop/worldwide/) the OS is and the work that this represents, I would love to support even Win XP, but I have to be realistic. This is something that should be provided by some contributor. ConEmu cannot be embed inside ecode since it requires a HWND (and ecode only has a single HWND for the complete window). Whatever we use to support terminals on Win 8.1 needs to directly replace [CreatePseudoConsole](https://learn.microsoft.com/en-us/windows/console/createpseudoconsole).
