### ISSUE TITLE
Include better monospaced fonts

### ISSUE THREAD

**Issue by superchick** [SpartanJ/ecode#226]
Noto Sans, Open Sans, and even Droid Sans (Fallback) are included. These are the fonts used by Google Android, so of course they support many languages (including Vietnamese, I think). As you are already using them, it makes sense to include the monospaced versions of them (Noto Sans Mono, Droid Sans Mono,...).

p/s: I'm not sure if Open Sans has a monospaced version, though.

**Comment by superchick** [comment]
The Jetbrains fonts (https://github.com/SpartanJ/ecode/issues/198) are also looking good, btw. Fira Sans also has a monospaced version as I know. But I don't know if they support Vietnamese. I have never tested them with Vietnamese text.

**Comment by SpartanJ** [comment]
Related to #208 . I might add a more complete mono font as default but I want to avoid adding too many assets that are not needed, I still want to keep the app as tiny a possible. Currently the biggest asset in our package is the color emoji font (~10MB compressed). But yes, it's possible to provide more fonts, but I cannot add every font that some of our users like because that will end up with too many fonts. But maybe later we can add a "font store" tool to automatically download the font from a font list provided by the project.

**Comment by superchick** [comment]
OK. Fonts are easy to add.
