### ISSUE TITLE
FR: Support for displaying a symbols table like Geany

### ISSUE THREAD

**Issue by ghost** [SpartanJ/ecode#264]
For example, if you open a C source file in Geany, it will list all of the symbols (variables, functions, etc.) in a table in the left pane. You can navigate between symbols with ease. Simply click on the symbol in the table, and it will jump to the exact location in the C source file. This feature on Geany also supports JSON.

**Comment by SpartanJ** [comment]
ecode already supports to inspect the symbols of a document with `ctrl+shift+p`, I'm hesitant of adding a Tree View since I don't find it particularly useful. But I'll add another filter to just list the functions, classes and structs and filter out all the irrelevant symbols. So: I'm not sure if I want this particular feature, I'll think about it.

https://github.com/SpartanJ/ecode/assets/650416/cba5f5a3-3b2d-4fbc-bc1d-4c0c58a37725

**Comment by iahung3** [comment]
> ecode already supports to inspect the symbols of a document with `ctrl+shift+p`
> 
>  2024-04-20_18-04-45.mp4

I don't know about this feature.

**Comment by SpartanJ** [comment]
This is has been implemented in a different way than Geany but provides the feature requested: 

https://github.com/user-attachments/assets/42e98f8f-735e-41ba-a6d0-6c784f78ff1a
