### ISSUE TITLE
[BUG] Locatebar empty in 0.6.0

### ISSUE THREAD

**Issue by NullPlane** [SpartanJ/ecode#303]
Locatebar (`MOD-K`) is empty when opened. No suggestions like `> , ft , : `
Tried to press tab and arrow keys but it seems to be not just hidden but not
generated at all. 

![image](https://github.com/user-attachments/assets/25600979-3571-48fa-83eb-18ca733c791a)

**Comment by SpartanJ** [comment]
Is there any open folder? Because that's the requirement and I think it changed the default behaviour from the last version. The only valid options from that list for non-opened folders would be the command palette, open documents and go to line. That needs to be fixed. If a folder has been opened then I'm not sure what's happening in your particular case.

**Comment by NullPlane** [comment]
Ya, no, no open folder &mdash; just the default environment.
