### ISSUE TITLE
[Lexers] Import new improvements from scintillua

### ISSUE THREAD

**Issue by Curculigo** [SpartanJ/ecode#313]
Scintillua is actively updated. orbitalquark managed to keep up with the latest keywords introduced by new language versions.

For example, ecode's cmake lexer and c++ lexer are lagging behind scintillua too much. It's time to sync with them!

https://github.com/orbitalquark/scintillua/tree/default/lexers

**Comment by SpartanJ** [comment]
I don't have time or interest to keep in sync anything from Scintillua since ecode does not support Scintillua lexers as we talked in the past. I don't have a problem updating the CMake keywords using the list from the Scintillua CMake lexer though, but you already created that issue [here](https://github.com/SpartanJ/ecode/issues/205). So I'll use that issue. 
I also have no problem improving any language based on the scintillua lexers, but I would do it only for particular cases and not as a general rule.
