### ISSUE TITLE
F5 build and run bug

### ISSUE THREAD

**Issue by Curculigo** [SpartanJ/ecode#328]
If use build and run feature, it will split into two panes: one for files, one for terminals. If don't click into the current file, new file will be opened in the terminal pane.

**Comment by SpartanJ** [comment]
It's not clear what you're asking or requesting, please rephrase it. New Terminals can have different behavior that can be configured on the Terminal settings menu, by default a new terminal will open in a vertical split panel but can be changed:
![Screenshot_20240902_191150](https://github.com/user-attachments/assets/b4cdfcd9-e8e3-4052-b874-857ab0fb5e19).

New files will be opened in the last active split, this is correct, if your terminal was active and tried to open a new file, it must open in that split.

**Comment by Curculigo** [comment]
I didn't change anything from the default behavior with is two split panels. When press F5, the terminal tab created will get focus. If I don't click to the file tab to have the focus back to the panel contains the files, new files will be opened in the panel for terminals.

**Comment by SpartanJ** [comment]
This is the expected behavior. New files or terminals will open on the last focused split / panel.

**Comment by Curculigo** [comment]
> This is the expected behavior. New files or terminals will open on the last focused split / panel.

This will mess up files and terminals. Everything will become a mess!

**Comment by Curculigo** [comment]
Why don't use the Terminal tab in the bottom like other editors and IDEs? Terminal in a file tab is nonsense.

**Comment by SpartanJ** [comment]
You can still use the terminal from below that does not share the splitter (Alt+3), I personally don't like it because it won't display much content since in terminals it's more important the vertical space than the horizontal. The splitter is perfectly usable the way it's, you just need to get use to navigating the editor with the keybindings provided (or change them ofc), you can switch the focus from panels with ctrl+shift+j (left) and ctrl+shift+l (right).
