### ISSUE TITLE
Unable to view the full diagnostic by clangd

### ISSUE THREAD

**Issue by Curculigo** [SpartanJ/ecode#335]
The diagnostic by clangd is in red color. There is no horizontal scrollbar.

**Comment by Curculigo** [comment]
Yes, I mean `code lens`.

**Comment by SpartanJ** [comment]
> Btw, is it possible to turn off code lens?

Sure, it's a linter feature so you need to go to `Tools -> Plugin Manager -> Select "Linter" -> click "Preferences"` and then set `enable_error_lens` to `false`.

All plugins options are explained in ecode's README [here](https://github.com/SpartanJ/ecode/?tab=readme-ov-file#plugins). You have plenty of configuration there, but lacks some visibility, that needs to be improved.

For the moment I won't change its current behavior, it's intentional to be just a quick preview, I don't like changing the document view-port size over something that it's not part of the document, I could add a mouse hover over the lens zone and display the same error than the text zone, but I don't see a good reason to do it, I might add it though.
