### ISSUE TITLE
Be a hex editor

### ISSUE THREAD

**Issue by chatchoi** [SpartanJ/ecode#348]
Or be more intelligent to check that the file I dragged into it is a binary file and can't be opened in text mode. I want to drag this ODT file into LibreOffice because the default program to open this file extension is MS Office and the path is too long to use the Open File dialog. I don't know why I wrongly dragged it into ecode.

**Comment by Curculigo** [comment]
ecode can open some binary files, most notably images.

**Comment by chatchoi** [comment]
How many images format are supported? I tried to drag a WEBP but it can't open.

**Comment by mh466lfa** [comment]
I prefer the `open anyway` behavior of this text editor. Geany for example will refuse to open the file if it can't recognize the encoding (the file is plain text and of course not binary). It will not even try!

If I have a mixed-encoding text file, and if the text editor agrees to open it anyway instead of considering it to be corrupted or in unknown encoding and refuses to even load it, I at least can recover some content of it (the UTF-8 part, ASCII, or plain English characters as you prefer how to call it).

**Comment by Curculigo** [comment]
> How many images format are supported? I tried to drag a WEBP but it can't open.

I don't know. I can confirm that it can open PNG, JPEG, and GIF (but there is no animations, only a static frame).

**Comment by SpartanJ** [comment]
My opinion is basically the same as @mh466lfa . It behaves exactly how I want it to behave. ecode is a text editor, there are many good hex editors out there and I don't think this is relevant to the project (if you want a nice hex editor is a quite big project alone by itself, check [ImHex](https://github.com/WerWolv/ImHex) which is awesome).

> How many images format are supported?

png tga bmp jpg gif (no animated) dds psd (basic support) hdr pic pvr pkm svg (no text or textures) and qoi

> I tried to open a SVG image but ecode will open it as text.

Which is correct because SVG files are just XML files, you can preview the SVG by right clicking in the document and "Show Image Preview", I use it all the time. This is 100% intentional.

> I tried to drag a WEBP but it can't open.

I might add webp in the future, but webp specification is huge and webp is a quite big library, I have some webp basic support implementation somewhere but I never integrated it because it's too limited ([this one](https://github.com/matanui159/jebp)). Someone needs to implement an easy to integrate and lightweight decoder in C/C++ for webp.
