### ISSUE TITLE
[0.4.6] Zombie OmniSharp processes

### ISSUE THREAD

**Issue by andy0x10** [SpartanJ/ecode#61]
I'm using Windows, and each time I quit ecode the OmniSharp process persists.
I have to kill those processes manually if I want to update ecode, as the system hasn't released locks cleanly on the ecode.exe

I'm not sure it's any use, but here's my log:
[ecode.log](https://github.com/SpartanJ/ecode/files/10805327/ecode.log)

Thanks,

**Comment by SpartanJ** [comment]
Ugh, OmniSharp seems to refuse to be killed for some reason, I don't know why and what is different from other LSPs. I'll take a look...

**Comment by SpartanJ** [comment]
Hi Andy!
Here's a build with the fix, your logs actually helped me: [ecode-windows-0.4.6-x86_64.zip](https://github.com/SpartanJ/ecode/files/10810272/ecode-windows-0.4.6-x86_64.zip), thanks!
BTW, you are basically not using OmniSharp at all. OmniSharps needs to find a solution or project file in order to function, otherwise, it won't do anything. I think that Unity can automatically create the solution file based on this [link](https://docs.unity3d.com/Manual/VisualStudioprojectgenerationWindows.html).

**Comment by andy0x10** [comment]
Thanks, yes I can confirm that fixes it :)
