### ISSUE TITLE
doesn't support Chinese

### ISSUE THREAD

**Issue by liujiaqi222** [SpartanJ/ecode#7]
Chinese characters are garbled

**Comment by Jiffies-Duke** [comment]
Please try to change the fonts of editor and UI to, say, Sarasa Mono SC. The default font contains no Chinese characters.

**Comment by SpartanJ** [comment]
ecode currently supports Chinese characters only using custom fonts that properly support CJK (Chinese, Japanese and Korean) characters. As @Jiffies-Duke suggested, `Sarasa Mono SC` will work just fine. The editor will complain that it does not recommend using a non-monospaced font since it will have an impact on the editor's performance (this is because of some design decisions). CJK fonts aren't monospaced because any CJK character is rendered as 2 characters width of a common ANSI character.
I'll try to clarify how to render CJK characters in the README. And in the future, I'll work for better support of wide characters in the editor (it should come out of the box).
The terminal currently supports wide characters out of the box, and Chinese will be rendered correctly.

**Comment by SpartanJ** [comment]
I decided to enable CJK characters out of the box at the expense of the performance of the application. I'll work to improve the performance when using fallback fonts, I've already been preparing something these days that could replace the current text renderer for the editor and fixes the performance issues.
