### ISSUE TITLE
Feature Request: Find only in selection

### ISSUE THREAD

**Issue by emeraldtip** [SpartanJ/ecode#72]
Would it be possible to make the find and replace tool only search and replace inside the selection, if a selection has been made?

**Comment by SpartanJ** [comment]
The feature already exists:

https://user-images.githubusercontent.com/650416/223511524-187cb7f1-dde8-4c45-a531-6f158ab776e0.mp4

Steps:
Select the range you want to search and replace -> Ctrl/Cmd + F -> set your find and your replace -> Replace all (Ctrl/Cmd + Shift + R)

**Comment by emeraldtip** [comment]
Oh nvm then, I was getting confused by the highlighting, as it highlights the results outside of the search aswell, but doesn't actually replace them

**Comment by emeraldtip** [comment]
I also just discovered that the search highlighting is overall a bit broken as when I have the case sensitive checkbox unchecked, the highlighting still matches the case even if it replaces the things without caring about case:
![image](https://user-images.githubusercontent.com/48155462/223534794-fcd9f026-ad3c-4e2c-8508-3d377203832f.png)

**Comment by SpartanJ** [comment]
I don't agree that it should only highlight the results in the selected range, I think it's actually useful to visualize if you're missing something in your selection, but it's debatable haha.

Regarding the other comment, it's kind of confusing because what it's being highlighted is the selection match, not the find results. ecode currently does not highlight the match results, that feature is pending.

**Comment by SpartanJ** [comment]
Added an issue to fix this.
