### ISSUE TITLE
Plug-in Architecture Question

### ISSUE THREAD

**Issue by TerminalFi** [SpartanJ/ecode#87]
How or what is the end goal for plug-in architecture?

Is it expected plugins must support LSP no matter what the plug-in does ?

Are plugins supported i any language ? Hot reloadable. ?

I really like the idea of this editor. It reminds me of sublime (which is my primary editor) but is open source. I'd like to contribute if I knew more of the plug-in arch plans

**Comment by SpartanJ** [comment]
Hi!

> How or what is the end goal for plug-in architecture?

The end goal is to expand the editor's capabilities. At the moment the plugin architecture is focused mainly on the editor view and document. To give you an idea [here](https://github.com/SpartanJ/eepp/blob/cdd91e904afe888c1cbb791e0e015e86dd25cdcc/include/eepp/ui/uicodeeditor.hpp#L33) you can see the basic interface to create an editor. But the plugin basically can modify anything from the UI, several features are already available but are not being used (for example, a tab bar in the side panel, or registering a gutter in the editor view to expand its capabilities). As for the moment all plugins are native code, so it's also expected that the plugins are delivered as part of the ecode package.

> Is it expected plugins must support LSP no matter what the plug-in does ?

It's not necessary. It's not a requirement nor it's expected to know about the LSP existence. But there's an API for intercommunication between plugins that allows a plugin to basically consume some LSP messages without knowing about the LSP existence or interacting with it directly. [Here](https://github.com/SpartanJ/eepp/blob/cdd91e904afe888c1cbb791e0e015e86dd25cdcc/src/tools/ecode/plugins/pluginmanager.hpp) you can see the basic functionality.

> Are plugins supported i any language ?

Not for the moment. Only C++ native code. I'll consider adding WASM support in the future when the plugins API stabilize.

>  Hot reloadable. ?

That's the plugin dutty, currently, all the plugins are at least able to be enabled and disabled during runtime. Configuration changes aren't being reloaded in real-time but it's very easy to achieve. I kind of forgot about implementing it, I'll fix it soon. I consider a basic requirement that the plugin must be able to be reloaded in runtime.

> I really like the idea of this editor. It reminds me of sublime (which is my primary editor) but is open source. I'd like to contribute if I knew more of the plug-in arch plans

Thanks! The idea is to have an open-source alternative to something similar to Sublime (which is a fantastic editor) plus add some new ideas to the code editor's space. It will take time to have feature parity with Sublime since Sublime has many years of development and a huge community. But we kinda have to start somewhere. A minor difference from Sublime that I'm trying to achieve is to have many features enabled out of the box. I want to have a set of plugins that are actually core to the editor but they can be disabled if the user wants to. I think that a good LSP integration is central these days to have a good user experience (the next release will have many pending features regarding this). Having the LSP protocol implementation almost complete I'm looking into starting working in a [DAP](https://microsoft.github.io/debug-adapter-protocol/) plugin and a Git integration plugin. I was casually checking [GitGutter](https://github.com/jisaacks/GitGutter) that I discovered by checking your profile that it looks great for inspiration, I would love to have something similar in ecode. I think that with those two plugins being implemented, ecode will be in a great spot feature-wise. But given that I'm currently the only developer everything takes time (this is just a side project that I work on in my free time). I would love to get some collaborators, but I understand that the codebase is very complex and the learning curve could be steep. I'm more than willing to help any collaborator, so let me know if you're interested and I'll guide you as much as I can.

**Comment by TerminalFi** [comment]
Well, firstly..I really appreciate the response ! It was much more than I had expected and is very detailed. 

On the plug-in side of things, what you said makes sense, having a core set that is built in and then allowing further plugins to be built to extend functionality. I'll definitely look over the links you provide to get a better understanding of what is going on and how you've got it implemented. 

To be clear, I've only ever written a little bit of cpp, and I'm more heavily involved in golang and python on a regular basis. 

However, I would like the challenge of contributing. With that, bear with me (I also code in my free time..which comes sparingly sometimes) as I try to get acquainted with the codebase. 

Would love to take up a challenge and or implement something simple to start. 

I was even considering taking up Copilot integration as a starting point. We'll see !

**Comment by TerminalFi** [comment]
@SpartanJ 

Looking to start getting familiar with the codebase. I am attempting to build on an M1

```
premake5 --with-mojoAL gmake2
ERROR: Couldnt find any backend. Forced SDL2.
Using SDL2 backend
Building configurations...
Running action 'gmake2'...
Done (1971ms).
make -C make/macosx all
==== Building SOIL2-static (debug_x86_64) ====
==== Building glew-static (debug_x86_64) ====
==== Building mbedtls-static (debug_x86_64) ====
==== Building vorbis-static (debug_x86_64) ====
==== Building pugixml-static (debug_x86_64) ====
==== Building zlib-static (debug_x86_64) ====
==== Building libzip-static (debug_x86_64) ====
==== Building libpng-static (debug_x86_64) ====
==== Building freetype-static (debug_x86_64) ====
==== Building chipmunk-static (debug_x86_64) ====
==== Building jpeg-compressor-static (debug_x86_64) ====
==== Building imageresampler-static (debug_x86_64) ====
==== Building mojoal-static (debug_x86_64) ====
mojoal.c
../../src/thirdparty/mojoAL/mojoal.c:64:10: fatal error: 'SDL2/SDL.h' file not found
#include <SDL2/SDL.h>
         ^~~~~~~~~~~~
1 error generated.
make[1]: *** [../../obj/macosx/x86_64/debug/mojoal-static/mojoal.o] Error 1
make: *** [mojoal-static] Error 2
```

Any ideas?

**Comment by SpartanJ** [comment]
> Would love to take up a challenge and or implement something simple to start.

Excellent!! Maybe you can start writing a generic module that implements the feature that you are planning, and later I can help you "connect the dots" with the editor, to display or run that functionality.

> I was even considering taking up Copilot integration as a starting point. We'll see !

That would be amazing!

> I rather meant is the plan to allow adding and removing plugins without editor restart a plan or will installing and or removing a plug-in require editor restarts.

As for the moment the plugins come with the editor since they are native code. I could load external dynamic link libraries but I did not take the time to look at it, since I'm the only maintainer and all plugins are part of the package. Anyway, this is kind of intentional too, because I would like to keep the plugin ecosystem under control, but I'm experimenting, and this could change in the near future. What I mean is that i want to have the ecosystem under control to keep the code quality of the plugins. Having a too-open ecosystem tends to taint the original product/app to a point that sometimes is really inconvenient, editors tend to become a big mess and make the whole app more unstable. What I would like to try is to allow plugins but under supervision, that would be something like: if someone wants to add a plugin, it will send a PR to the project maintainers, and those maintainers will certify that the implementation is good/optimal (for example, that it's correctly threaded and the functionality don't block the main execution thread). Once is approved the code will be merged to the main repository, and the plugin will be available to all users, probably disabled by default (unless it's a core functionality, like git integration).

**Comment by SpartanJ** [comment]
> @SpartanJ
> 
> Looking to start getting familiar with the codebase. I am attempting to build on an M1
> 
> ```
> premake5 --with-mojoAL gmake2
> ERROR: Couldnt find any backend. Forced SDL2.
> Using SDL2 backend
> Building configurations...
> Running action 'gmake2'...
> Done (1971ms).
> make -C make/macosx all
> ==== Building SOIL2-static (debug_x86_64) ====
> ==== Building glew-static (debug_x86_64) ====
> ==== Building mbedtls-static (debug_x86_64) ====
> ==== Building vorbis-static (debug_x86_64) ====
> ==== Building pugixml-static (debug_x86_64) ====
> ==== Building zlib-static (debug_x86_64) ====
> ==== Building libzip-static (debug_x86_64) ====
> ==== Building libpng-static (debug_x86_64) ====
> ==== Building freetype-static (debug_x86_64) ====
> ==== Building chipmunk-static (debug_x86_64) ====
> ==== Building jpeg-compressor-static (debug_x86_64) ====
> ==== Building imageresampler-static (debug_x86_64) ====
> ==== Building mojoal-static (debug_x86_64) ====
> mojoal.c
> ../../src/thirdparty/mojoAL/mojoal.c:64:10: fatal error: 'SDL2/SDL.h' file not found
> #include <SDL2/SDL.h>
>          ^~~~~~~~~~~~
> 1 error generated.
> make[1]: *** [../../obj/macosx/x86_64/debug/mojoal-static/mojoal.o] Error 1
> make: *** [mojoal-static] Error 2
> ```
> 
> Any ideas?

I was just writing to you haha. Yes, you will need to install the SDL2 package (you can just use brew or some package manager). You know I never build ecode for an arm64 macOS, so you're probably the first. I don't have an arm mac at my disposal at the moment. I was going to try to cross-build it.

**Comment by SpartanJ** [comment]
I'll close this for the moment. Any king of question should go to the [Discussions](https://github.com/SpartanJ/ecode/discussions) section. Thanks
