### ISSUE TITLE
LSP support for Objeck

### ISSUE THREAD

**Issue by objeck** [SpartanJ/ecode#95]
Basic LSP messages like 'hover', 'didchange', 'didsave' and 'publishdiagnostics' all work fine. When I try to search symbols, I get an error stating that the LSP server is not running; however, it is. Any ideas? 

Last, when edits are made, are files locked until they are saved? I get an error that I cannot read the file, but once saved (and I reread) behavior returns to normal. I code around this. However, I have run into this issue with other editors.

**Comment by SpartanJ** [comment]
> When I try to search symbols, I get an error stating that the LSP server is not running; however, it is. Any ideas?

That's the message you'll get when the server closed unexpectedly (crashed). ecode logs with `-ldebug` flag should help you, sometimes the server report the issues. Or you might debug the LSP server by running it manually and testing it with TCP instead of stdio.

> Last, when edits are made, are files locked until they are saved?

No locks, edits are only in-memory operations.

> I get an error that I cannot read the file, but once saved (and I reread) behavior returns to normal.

Mmmhh... the LSP server should never read the file from the disk. It should keep the document state in memory and apply the changes required from the client. That's probably an incorrect implementation. LSP servers must be able to work without direct access to the file system, the protocol is designed in that way to allow the server to run separately from the client.

**Comment by objeck** [comment]
Fixed the issue https://github.com/objeck/objeck-lsp/commit/a7569dfdf8f907ffa97ecea826a7049d2800e756

**Comment by objeck** [comment]
> Thank you, I fixed the issue [objeck/objeck-lsp@a7569df](https://github.com/objeck/objeck-lsp/commit/a7569dfdf8f907ffa97ecea826a7049d2800e756). I had a dependency on an option parameter.

BTW - I do reread from disk when I get a save message from the client. It is a sync point for the memory document in use.

**Comment by SpartanJ** [comment]
Great that you were able to fix it with a minor patch!

Regarding the `textDocument/didSave` capability you might be able to sort the issue by requesting the client to send the document text with the event, setting the [server capability ](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocumentSaveRegistrationOptions) `includeText` as `true` and then processing the [text](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#didSaveTextDocumentParams) field sent by the client as the document synchronization.
